:source-highlighter: pygments

= Vanubi Manual

== Download & Installation
keywords:[downloads installation building make clone]
.Download the latest release of Vanubi, build it and launch it

[source,console]
:args: -O style=native,noclasses
-------
# apt-get install autotools-dev libtool valac libgtksourceview-3.0-dev libvte-2.90-dev libwnck-3-dev
$ git clone http://github.com/vanubi/vanubi.git
$ cd vanubi
$ ./autogen.sh
$ make
$ gui/vanubi
-------

Installation is not yet supported. Vanubi is only tested on Linux systems.

Make sure to have the most recent Vala compiler at your disposal.

== Key/mouse bindings
keywords:[keys keybindings mousebindings mouse]
.Basics of key and mouse bindings

Most of programming in Vanubi happens on the keyword. It's important to have meaningful key bindings. In this regard, Vanubi inherits some of Emacs key bindings.
Key bindings are made up of one or multiple key combinations: for example `C-x C-s` has to be interpreted as press `Ctrl+x` then press `Ctrl+s`, or keep `Ctrl+x` pressed then press `s`.
Pressing them at the same time is not needed, the important thing is to press keys in the correct order.

Currently supported modifiers are Shift (S-) and Ctrl (C-). Note that `C-x k`, `C-x C-k` and `C-k` and three different key bindings.

== Ideas and principles
keywords:[ideas principles todos questions answers]
.Rationale and mindset behind the project

Principles:
	
- Simple, complete, keyboard based, intelligent, unobtrusive, well integrated
- Implement what you really use, not what you don't use
- Implement what you expect, not what other editors do
- Implement what you really need, not what you think you need
- Monolithic, no plugins, things must just work and be consistent
- Must be complete, yet fast to open a single file for editing
- File/directory-based settings, not project-based
- Intelligent defaults based on the current opened file context
- Easy to use contextual help... we can't remember all the keybindings
- Semantic support for languages similar to eclipse but much less invasive, and faster from the user perspective
 
Ideas:
	
- Transparently open remote files on your local editor
- Code fold / Comment fold
- Support GDB, Hexdump, GPG, Patch/Diff, Git, Git-bz and a bunch of other tools
- Integrate with libinfinity for real-time collaborative editing

== Commands
keywords:[commands help controls]
.Get help, run commands and learn key bindings

Vanubi is controlled by commands issued by the user. A command might be activated by a key binding, a mouse action, or programmatically by invoking a command using `C-h` (the help command).
Not all commands have key bindings, however by using `C-h` it gets very handy to run unusual commands.

== List of basic commands
keywords:[commands keyboard mouse bindings keybindings basics]
.Basic key and mouse binings along with command names

Below a list of basic keyboard bindings with relative commands to get started:

[frame="topbot",cols="9monospaced,20,70",options="header"]
|==================
| Combo | Command | Action
|C-h|-|			   Most important: search for commands and configure the editor
|C-x C-c|quit|          Quit vanubi  
|C-g     |-|         Abort  
|ESC      |-|        Abort  
|C-x C-f   |open-file|       Open file  
|C-x C-s    |close-file|      Save file  
|C-x b       |switch-buffer|     Switch buffer  
|C-x k        |kill-buffer|    Kill buffer  
|C-x 1         |join-all|   Join all the splits  
|C-x C-1|join|          Join the current split only  
|C-x 2   |split-add-bottom|         Split horizontally (one editor up, one down)  
|C-x 3    |split-add-right|        Split vertically (one editor left, one right)  
|TAB       |indent|       Indent current line  
|C-TAB |tab| Insert a tab character
|F9         |compile-shell|      Run compile shell
|C-c C-c     |comment-region|     Comment a region  
|C-n           |forward-line|   Go to next line  
|C-p            |backward-line|  Go to previous line  
|C-k    |kill-line-right|          Delete line contents on the right of the cursor
|C-x C-k|kill-line| Delete the current line
|C-e     |end-line|         Go to the end of line  
|C-a      |start-line|        Go to the head of line  
|C-space   |select-all|       Select all text  
|C-l        |next-editor|      Iterate the editors on the right  
|C-j         |prev-editor|     Iterate the editors on the left  
|C-s          |search-forward|    Search forward  
|C-r           |search-backward|   Search backward  
|C-d|delete-char-forward|              Delete the char next to the cursor
|Alt+down       |-|  Swap current row with the row below  
|Alt+up          |-| Swap current row with the row above    
|==================

Mouse bindings:

[frame="topbot",cols="9monospaced,70",options="header"]
|==================
| Combo | Action
|C-scroll| Increase/decrease the font size
|==================

== Fuzzy search
keywords:[fuzzy searching]
.Find and match anything with intelligent search

All of the matching and search components of Vanubi use fuzzy search when possible. Fuzzy search means you can type only part of the text, and it will match and sort documents accordingly.
For example the query 'fb' will match 'foobar'. Sorting takes in consideration how and where the query pattern matches the document to obtain the best result.

== Dealing with files
keywords:[opening save saving files scratch]
.Open, save and find files in your projects

At start you are prompted to edit `*scratch*`. This is not relative to any particular file, it exists as a temporary buffer for your own notetaking.

You can open a file for reading or create a new file with `open-file` (`C-x C-f`). You can type only part of the file and Vanubi will fuzzy search through file names.
It is also possible to fuzzy search through sub directories. For example '/u/b' will match all sub directories like `/usr/bin`, `/usr/sbin`, `/run/dbus`, `/usr/lib`, etc.
The tidle (`~`) is expand to the user home directory.

You can save a new or existing file being edited using `save-file` (`C-x C-s`). The file will be overwritten if it already exists.

If a file has been edited elsewhere and you want to reload it, it is possible with `reload-file`.

== Manage opened files
keywords:[buffers views editors files switch tabs manage]
.Switch between opened files, split views and more

A buffer (or editor) is a view of a file being edited. It is possible to split buffers horizontally with `split-add-bottom` (`C-x 2`) or or vertically with `split-add-right` (`C-x 3`).
This allows you to open two views for the same file.

You can switch between files within a view using `switch-buffer` (`C-x b`). Note that the first file in the switch buffer completion is the last file you edited in that view. That allows you to quickly switch between two files repeatedly within the same view, and to keep focus on the files you are recently editing.

To close a buffer you can issue `kill-buffer` with `C-x k`. If the closed buffer was the last visible buffer for a file, the file will be removed from Vanubi and won't be visible when switching buffers anymore.

== Shell terminals
keywords:[compilation shell build projects errors]
.Open a shell, build your project and jump to errors

Currently shell terminals can be opened with `compile-shell`. It will open a shell intended for compilation, though it's a general purpose shell.
Each file has its own shell, and the current working directory is saved for that file so that when you reopen Vanubi, the shell will initially open on your last working directory.

Vanubi will parse the output of compilation and try to guess possible errors. You can navigate through errors with `next-error` (`C-'`) and `prev-error` (`C-0`).

== Pipe-shell commands
keywords:[pipelining shell commands execution]
.Pipe text to a shell command and do powerful things

Pipe-shell commands allow you to pipe the current contents (being saved or not) to a command, and do something with the output of the command.
Additionally, `%f`, `%s` and `%e` are replaced with the filename, selection start and selection end respectively in the shell command.

In particular, `pipe-shell-replace` allows you to create complex scripts to edit the current edited buffer as you wish.
While `pipe-shell-clipboard` allows you to call commands like `pastebinit` to share part or the whole buffer, or `asciidoc -b html5 - > tmp.html && xdg-open tmp.html` to render an asciidoc in your browser.

== Sessions
keywords:[sessions restore restoring]
.Save your workspace and restore it later with sessions

Vala keeps track of opened files and the current location of your cursor, and saves this information in the `default` session. After opening Vanubi, you can restore the last session with `restore-session`.
It is possible to save a named session with `save-session`, which you can later open with `restore-session` by specifying the name of the session.

== Marks
keywords:[marks marking jumping code places]
.Mark your places in the code and jump between locations

Vanubi keeps a stack of marks among files that are set by the user, and are never implicitly set.
You can set a mark on the current location with `mark` (`C-m`). You can go to the last mark set with `prev-mark` (`C-,`). Marks are added to a stack, so you can go back to previously set marks, and go forward with `next-mark` (`C-.`), until no more marks are available.

== Vade scripting language
keywords:[vade language programming scripting scripts]
.Embed simple expressions anywhere to do useful tasks

Vade is a simple language for writing expressions in Vanubi.

=== Syntax

==== Friendly syntax explanation

In Vade everything is an expression, and each expression evaluates to a value.

An expression is a sequence of sub expressions separated by `;`.

[source,javascript]
:args: -O style=native,noclasses
-------
expr1 ; expr2; ...; exprN
-------

Expressions can be `if` expressions, with an optional `else` branch:
	
[source,javascript]
:args: -O style=native,noclasses
-------
if (condition) true_expr else false_expr
-------

Usual assignment, arithmetic and relational expressions are supported. Assignment is done with `=` as follows:
	
[source,javascript]
:args: -O style=native,noclasses
-------
identifier = value
-------

If an expression is a function (like `concat`) it is possible to call such a function with arguments separated by `,` as follows:

[source,javascript]
:args: -O style=native,noclasses
-------
concat(arg1, ..., argN)
-------

You can define your own functions as follows:

[source,javascript]
:args: -O style=native,noclasses
-------
func = { param1 param2 | body }
func_without_params = { body }
-------

That is, enclosing an expression between braces will create an anonymous function.

==== Formal syntax

Below a BNF-like description of the language.

[source,text]
----------
expr = seq
seq = nonseq [ ';' seq-expr ]
nonseq = binary | if

if = 'if' '(' expr ')' primary [ 'else' primary ]

primary = assign
assign = rel [ ('='|'+='|'-='|'*='|'/=') assign ]
rel = add [ ('=='|'!='|'>'|'>='|'<'|'<=') rel ]
add = mul [ ('+'|'-') add ]
mul = unary [ ('*'|'/') mul ]
unary = simple | ('-','++','--') simple

simple = simple-init [ simple-access ]*
simple-init = identifier [ ('++'|'--') ] | function | '(' nonseq ')' | literal
simple-access = '.' identifier | call
call = '(' [ arguments ] ')'
arguments = nonseq [ ',' nonseq ]*

function = '{' [ parameters '|' ] expr '}'
parameters = identifier [ ' ' identifier ]*

identifier = ALPHA [ ALPHANUM ]*
literal = num | string
num = DIGIT* [ '.' DIGIT* ]
string = "'" escaped-string "'"
----------

=== Semantics

Every expression in Vade evaluates to a value. The type of a value is either a function or a string. If the value is a string, it is interpreted as a number or a boolean depending on the operation performed on the value.

An expression is evaluated within a `scope`. A scope is a mapping between registers (or variables) and values. Registers are referenced by identifiers in the code.

An expression made up of a sequence of expressions (`expr1; ..., exprN`) will evaluate to the value of the last expression.

.Using registers and evaluating the last expression
=============

The expression below will evaluate to `10`:
	
[source,javascript]
:args: -O style=native,noclasses
----------
a = 4; b = 6; a+b
----------

=============

Referencing a non-existant register will evaluate to an empty string (or 0 if used as a number).

.Using undefined registers
=========

The expression below will evaluate to `1`:
	
[source,javascript]
:args: -O style=native,noclasses
----------
++foo
----------
=========

In the Vanubi editor, a `base scope` is created and all top-level expressions will share the same scope. Therefore a register assigned in an expression will then be reusable within the application when evaluating another expression at a later time.

Functions in Vade run in a scope which is created starting from the scope in which they are defined (`parent scope`).
Assigning a register `reg` inside a scope with a parent scope follows the rules below:
	
	1. If `reg` is defined in the scope, then the value within the scope is updated.
	2. Otherwise, if `reg` is defined in the parent (or any ancestor) scope, then `reg` is updated in that parent (or ancestor) scope.
	3. If `reg` is not defined in the parent (or ancestor) scope, then `reg` will be defined in the current scope (`local` to the function).
	
This allows for simple access to top-level registers, yet keeping the definition of new registers local to the function scope.
Parameters of function will define a local register in the function scope, hiding any register in the parent scope.

.Global and local registers
==========

The expression below will evaluate to `5` (not `7`) because `b` is zero in the parent scope:

[source,javascript]
:args: -O style=native,noclasses
------
a = 3; f = { b = 2; a = a+b }; f(); a+b
------

==========